import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import Navbar from "@/components/Navbar"; // 👈 import Navbar
import GlobalRedirectGuard from '@/components/GlobalRedirectGuard'
import Footer from '@/components/Footer' // ✅ Import



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tanmore – Leather Marketplace",
  description: "Google-only auth eCommerce platform",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          <GlobalRedirectGuard /> {/* ✅ Moved inside */}
          <Navbar /> {/* 👈 Sticky navbar */}
          <main className="min-h-screen">{children}</main>
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}


// this is wrong you can not use use client in server component 

// 'use client'

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { GoogleOAuthProvider } from '@react-oauth/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Tanmore – Leather Marketplace',
//   description: 'Google-only auth eCommerce platform',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <GoogleOAuthProvider clientId="YOUR_GOOGLE_CLIENT_ID">
//           {children}
//         </GoogleOAuthProvider>
//       </body>
//     </html>
//   )
// }


// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
